services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mp_dicri_db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=MpStrongPass123*
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  api:
    build: ./backend
    container_name: mp_dicri_api
    env_file:
      - ./backend/.env
    depends_on:
      - db
    ports:
      - "3001:3001"

  web:
    build: ./frontend
    container_name: mp_dicri_web
    depends_on:
      - api
    ports:
      - "3000:80"

volumes:
  sql_data: